/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BudgetSettings {
    #[serde(rename = "date_format")]
    pub date_format: Box<crate::models::DateFormat>,
    #[serde(rename = "currency_format")]
    pub currency_format: Box<crate::models::CurrencyFormat>,
}

impl BudgetSettings {
    pub fn new(date_format: crate::models::DateFormat, currency_format: crate::models::CurrencyFormat) -> BudgetSettings {
        BudgetSettings {
            date_format: Box::new(date_format),
            currency_format: Box::new(currency_format),
        }
    }
}


