/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SaveAccount {
    /// The name of the account
    #[serde(rename = "name")]
    pub name: String,
    /// The account type
    #[serde(rename = "type")]
    pub _type: Type,
    /// The current balance of the account in milliunits format
    #[serde(rename = "balance")]
    pub balance: i64,
}

impl SaveAccount {
    pub fn new(name: String, _type: Type, balance: i64) -> SaveAccount {
        SaveAccount {
            name,
            _type,
            balance,
        }
    }
}

/// The account type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "checking")]
    Checking,
    #[serde(rename = "savings")]
    Savings,
    #[serde(rename = "creditCard")]
    CreditCard,
    #[serde(rename = "cash")]
    Cash,
    #[serde(rename = "lineOfCredit")]
    LineOfCredit,
    #[serde(rename = "otherAsset")]
    OtherAsset,
    #[serde(rename = "otherLiability")]
    OtherLiability,
}

impl Default for Type {
    fn default() -> Type {
        Self::Checking
    }
}

